version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mi_mongo_db
    restart: always
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: loc8r
      MONGO_INITDB_ROOT_PASSWORD: loc8r
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: